-- MySQL Script generated by MySQL Workbench
-- 02/13/15 09:23:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';



-- -----------------------------------------------------
-- Table `chloeellis_0_db`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloeellis_0_db`.`guest` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(90) NULL DEFAULT NULL,
  `lastName` VARCHAR(90) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(90) NULL DEFAULT NULL,
  `address` VARCHAR(90) NULL DEFAULT NULL,
  `notes` VARCHAR(255) NULL DEFAULT NULL,
  `mealId` INT(11) NULL DEFAULT NULL,
  `plusOneId` INT(11) NULL DEFAULT NULL,
  `statusId` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `association` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chloeellis_0_db`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloeellis_0_db`.`meal` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chloeellis_0_db`.`plusone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloeellis_0_db`.`plusone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `guestID` INT(11) NOT NULL,
  `Name` VARCHAR(90) NULL DEFAULT NULL,
  `mealId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `guestkey_idx` (`guestID` ASC),
  CONSTRAINT `guestkey`
    FOREIGN KEY (`guestID`)
    REFERENCES `chloeellis_0_db`.`guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chloeellis_0_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloeellis_0_db`.`status` (
  `id` INT(11) NOT NULL,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
